### ISSUE TITLE
Unable to compile in Arduino IDE 1.8.13

### ISSUE THREAD

**Issue by AlbertWeterings** [xoseperez/espurna#2326]
**Question**
*A clear and concise description of what the problem/doubt is.*
**Unable to compile development version in Arduino IDE 1.8.13.**
**Screenshots**
*If applicable, add screenshots to help explain your problem.*
**sketch\libs/BasePin.h:12:26: fatal error: config/types.h: No such file or directory
 #include "config/types.h"**
**The file config/types.h is at the location but somehow the compiler can't get to it.**

**Tools used**
* *Desktop operating system*
**Windows 10 2004**
* *IDE & version*
**Arduino 1.8.13 portable**

**The problem can be solved by changing BasePin.h from:**
#include "config/types.h"
to
#include "../config/types.h"

But don't know if this has unwanted effects

**Comment by mcspr** [comment]
PIO vs. Arduino builders seem to differ where they actually do the build - PIO keeps CWD in the `code/espurna/`, while Arduino switches out into a separate temporary directory. Meaning, `config/types.h` is perfectly valid for GCC (since it is there...) when it can't the `code/espurna/libs/config/types.h`
